stages:
    - build
    - deploy

build:ubuntu:xenial:
    stage: build
    before_script:
        - sudo apt-get update
        - sudo apt-get -y install cdbs debhelper devscripts sed cmake build-essential pkg-config libprotobuf-c-dev libsqlite3-dev libsystemd-dev
    script:
        - dpkg-buildpackage -uc -us -b
        - rm -rf artifacts && mkdir -p artifacts
        - mv ../pdns-logger*.deb artifacts/
        - mv ../pdns-logger*.changes artifacts/
    artifacts:
        expire_in: 1 month
        paths:
            - artifacts/*
    tags:
        - ubuntu-16.04

deploy:ubuntu:xenial:
    stage: deploy
    tags:
        - ubuntu-16.04
    dependencies:
        - build:ubuntu:xenial
    script:
        - echo "Deploying to repository"
        - ls -la && pushd artifacts
        - /bin/sed -i.bak "s|Distribution. unstable|Distribution\: xenial|" *.changes
        - grep Distribution *.changes && /usr/bin/dput glab *.changes
        - popd
    only:
        - web # Pipelines run from the "Run Pipeline" button in Gitlab UI
